apiVersion: v1
kind: Secret
metadata:
    name: github-runner-secret
    namespace: boundcorp-dev
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:NSUVM5sY/972YfekxJ7Vuxu5FLmwnGxfidqmTh4=,iv:tzDe5Czzd8e+p77e/oWlM3UGC7SCTufBat38XzNOnmc=,tag:9IvY9UrtB4fFxhkmTAUkOA==,type:str]
    GITHUB_OWNER: ENC[AES256_GCM,data:N7NgxURWuNOvbD39gRs=,iv:8Ygh/prJI0bmIW4X4m8RBsvyTzWDxHgzhPH0XZ1PMG4=,tag:YnfVKQS6uyN05HUf2HbPfg==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Enfj,iv:Y1Tqn6v9NK0xmQlNftln6Fpzu6SneSgp32+yIpzCm7U=,tag:Y/FRvnJXdSxvkz7JFCR9xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOTFCbU5XN0I4dDdxVkE3
            TCtnc0ZsNlpOcWliMHYxNDZmT1AvNHM4TG5vCmpwaTd6V1ZHS25PcVZwMFFVT1FL
            SkxWbVErOFlueEl6Zm1icldTdFNENEEKLS0tIGtPY2JNQ3kxTWl4aWRtOXRXbWNC
            dUxEZ0YrbW90bHZlQU56bUdOTkcwczAK9tYqIYFW7Bx3LCwitq0GwHYveGdcT/bY
            6sTKrj5xyKnq1fWTTzkhJSioPubKKtwsS7ZJSO1odZTFdyYznX4N2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T22:17:53Z"
    mac: ENC[AES256_GCM,data:Lib8XDjPH7wcVSRttTDgE/QzhNVuYaoTN1gV5W0VMmd0DBtbSxuGTD8DD2GnliO00U7bAe3RrOLT/We2750OLuELqfQw6twesGpmB501vG3EPi3mTyCtdI2qkeznGnH7K9g8dg5hHsRk0GIQXO73009kN6wSQFCxFe5sk2ZB9lU=,iv:UGrYujinnFAsyIZQu7UzjfNfXKOQbhXNEL920wF2BuU=,tag:/ANZhQ8LfYYim+i92ra2Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
