---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-restarter
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: media
  name: jellyfin-restarter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-restarter
  namespace: media
subjects:
- kind: ServiceAccount
  name: jellyfin-restarter
  namespace: media
roleRef:
  kind: Role
  name: jellyfin-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin-restarter
  namespace: media
spec:
  schedule: "0 6 * * *"  # 6am PST/PDT daily
  timeZone: "America/Los_Angeles"  # This ensures proper PST/PDT handling
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jellyfin-restarter
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl:1.29
            command:
            - /bin/sh
            - -c
            - |
              echo "Restarting Jellyfin deployment at $(date)"
              kubectl rollout restart deployment/jellyfin -n media
              echo "Jellyfin restart initiated successfully"
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                cpu: 100m
                memory: 64Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            fsGroup: 1001
