---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: database
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-titan-hdd
  resources:
    requests:
      storage: 4Ti
