---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./crunchy/secret.sops.yaml
  - ./crunchy/helmrelease.yaml
  - ./crunchy/devboxergo-init.yaml
  - ./crunchy/cluster.yaml
