apiVersion: v1
kind: Secret
metadata:
    name: github-runner-secret
    namespace: boundcorp-dev
type: Opaque
data:
    GITHUB_OWNER: ENC[AES256_GCM,data:5z79cdFTk93bTo5QScUktNAXqbQ=,iv:/E014oXB+ENwF1ASPCnrVCTKQlCa8R8E6UVIVB4d6Ew=,tag:7HxOhPcHZRWhe0LJs6fo7w==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:rwki6Q==,iv:kJrh0oErIkLZInB6Fj9c50GqjxNp91suW2+tTsQXWAc=,tag:TYstDVdfT3QIkxvQ9RqJCQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:G0kMrwkbYO8o470ThW2G01Vgt78gUqiHCbA2tIUZD4LaZr6E68xqdbMXPSdJNwWiWBKCVoP/tpA=,iv:4Bb7mfWy5llp6RumNRA5Ld8tkUzu4AKI0w7wKUxvIuU=,tag:S107dGuCljn+Ez3q+xlqDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHgyRG1PcktVNy9ROVdr
            WTFhekFpQkxEOTJONEQrL2pWSTFJZkk1b213Cm5Yc2ZBWUtaSnlaemZVNkZxMklW
            NEFLeEZmUXhNdzNSSEFRQ283VnoyVTgKLS0tIDVwNTYvUHBaQnJhQnZXM3U3aTR3
            eHd6c0pXZ1VwUUg3VmtoaWhjZWNxNW8KcvNQKGAp4OJbUed5dwAVbw6QiCdZiVFj
            DHcH5gMD52a9Q7BTWB2M/fs1DGSz+7sXOiP9qsn4bwAWcqbPD9s+Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T19:05:46Z"
    mac: ENC[AES256_GCM,data:LcHdNLwkgbS96iSZZiO/Uz8XTQIwmd9O/bRzM8in2kN115TY+Gd3/Us7wmnT0z1C0iBqTzfywx7NQww0N13MwDKct0JmacSz2d/70VROUGGRz4ZaQEyZYmCCacWDgFMJfo9A52TILyOvlTTXe9AS4EGhM/zarjQ/FoJwlpf7Z6o=,iv:ODKb/4nzwe0wkL9VUBqtdjxudv7eqvJLbXrASWLxphM=,tag:KWc5vKL4nr0yzyUJ+RQWJg==,type:str]
    version: 3.13.1
