apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: token-collector
    namespace: tools
stringData:
    secret-key: ENC[AES256_GCM,data:gLYqH0Gb7pVsDA7GGdUekHNfXjPXLMZtWhlXYI3ZOUSR6/5X9JY5V6mVjLOkDlUtfNSjSTiORS16snpdmNBUInKyCQ==,iv:2NSVdfmPQagi15iKPC8yRJAR1YWcUC0SINu2ffhu0+U=,tag:tBZjUmHfRXIHs2uHuPzeKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMFBwYUh0dmdKMndySTdL
            WWxPM2lpSnZONlM2RmdyOWxRcnMvRFNFMFE4CnVJRHVpalZpMU02RFlMNkQvVVFI
            bENKa2k0TlJScGxIdWF2dEphVWNkNUkKLS0tIHVSZnV2aEIwbWVrckVNOGlPcmdL
            RnA0V3BicU5ydjgzR1d5eHhKMjBFU00K+vXlPNUJbyllipyBHzUkz/lTrYdHqnSg
            kqOBNpmTARdpIZtieFMsl0Jof7mpbx5UmZbIIUfiEjE/i0H1781Xdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T19:44:40Z"
    mac: ENC[AES256_GCM,data:jKuGxivgq2NOX5PRvBJRjdgR40AI6BzkUAa4cDfQrGb2x8HRxr8z+jOKlz/p9AmPm/O48qsrt/54WRqkVS8MN2yR6g0LiS2kFvGTuQsDSmuSkhdPS7zj9qLpXCk2TDBlRcwsIiWqCIHvB7hJ7ndo+5yy7sXHOECvr6Wk90s8lFM=,iv:2OzUlpI1+liKHU80bdl5Pq1HswhPIzkge6FtMIlmxhs=,tag:bvAXcmQfkLFvVST9+P/4SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
