---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: birdweather-media
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-titan-nvme
