apiVersion: v1
kind: Secret
metadata:
    name: birdweather-ingester
    namespace: home
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:eI49juUWTlpwhb9EDWbGNa5ESaC+gjjE,iv:/ZoVX2vz66efcd8BCE4HaYFzean3avIHFW17NWihh/Q=,tag:xtmIzjcZaVcbROgo3WVm8A==,type:str]
    station-id: ENC[AES256_GCM,data:9TzyJxc=,iv:wopx4FzJxRJP2l7UpUGV6S4oYR2TaBkjQlbsVK8njE4=,tag:j0TM8HQJf1T5ifQHE3N7TA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdk1wWElpaWc3SlRDaXU5
            MkRjNU1MdU9FcnlVOEJjVW1kTXljQmVkUm1ZCjVOamJWT3ZSVVNwYlJmejFBZjFG
            SGxpV3JrclBHcTlLMDlySm9qOFhEOWMKLS0tIFlFL3ZDdGFETmRlc3pYN3FETXRE
            N3VpSUhwYzUzRG9HbGlodWRULzVLMTgKkhTrWtNyY3OYBmQjezcz68SNxevkBWJK
            yzT/MGjO3flDu+GpRyWYvckkueDSOhEebhRNRwgseWlwth+j2rgV6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T03:52:15Z"
    mac: ENC[AES256_GCM,data:7pKRF8EuoXNZtO8C8ydZi7vrWnWI/b6ZEa2rDfa7qvPKvLuzmZAMV5T7Z+UDRknV2adKB5qFiyF2epb7ECntZB4Zu8q93pCphACvX/+z5DDubxvIabeGUEKUkbrduMH1E4geavlnvu5P8FkRU2w9XrdOpk8GAagP4gt6eVvueqc=,iv:MQTe0F05Y1J0YexUiK0x2kykE9+/s47rUaDpyXFWuSQ=,tag:i9jMEzf8pKH8Y9xGwGTIUg==,type:str]
    version: 3.13.1
