apiVersion: v1
kind: Secret
metadata:
    name: birdweather-ingester
    namespace: home
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:5VTQmcB/+9KVI5gyeBnUTqhg5JwqT61O,iv:BpTCxmnoZwqTgSNoIONW4eQpc/kpJruPP8zpqsuPTBE=,tag:J/SLhpmniGpchp2weY9CHw==,type:str]
    station-id: ENC[AES256_GCM,data:N3Sk1S8=,iv:gaQbv88KR4+Sq8IOSZffG3ZM82C8Ssp9FJj7RuaF8nQ=,tag:J6u9bYIFI671zwnEL31PKg==,type:str]
    openai-api-key: ENC[AES256_GCM,data:u5J6aD50D7iqKiWsHyz9h5ZbToc8sJMGmRtCRc8VaE0QC7mq7thc0E8XdapHDkunk3CwQsXfl+pIPX/6iZM9wcKGXDoTDYr/oNSfrEuCR/nXcNYq3QGc+UILoFGlzz293kvL1JtHU5mneDxRPZk2PjHcZTS3DV1QGmZG+z4ooA3is/U1PDBnsE//1XRKrAC5rAS1jkRNf8tzpdo2nqi4xMTr0/I=,iv:HtWFNrVHBoN3/oN8iluJpj5C4ZYF7xvp4RoJYPuij/4=,tag:q1rQ7GbN8gewQvBVKBM7vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeGRDYjRiVVdoNHFaQkp6
            YU1NVE9tbzFrakVjZVFIbGREQjhJL21kYlc0CkVEcTJMUkdFckFXY3R5OGhvWlVv
            VE1HTVQraGs4bFhIS1FFWE5OR1htYUUKLS0tIFpjbDhyWGZ0R1M0eTBCKzBEdlRZ
            YXAzVFR1Rkxic0E1R1Q0dlFXcDNmemsKtFAR89ZZK9Zz2OA98x1RZJ41Prtwaq0n
            QTvzQiEe7zTevCdk4mzSKpN7phxXiHGOBlNYKErMWZdSPLRK2PQZJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T17:29:57Z"
    mac: ENC[AES256_GCM,data:yXRvpkmgVVw/+ZfGMC0YP4/0DgZpC9d/B8mTwvApcWc4ttvirewHPOZttkO4VyeJ73716toI8KxBwZioQv6tmoUK5vrDZc2LZUN/LPdLm7aAhByiQbF+41smK5fO68W/DJuSykWSZwM3Wsy2YCP9VdQuk2RbV+vkkH2a3+fZdf8=,iv:vMC9uyYIPoevUEt7wLqyOba3QALhVfzEO7kzVXw6ai8=,tag:DCrc0XEFGZl5WIj80dnJww==,type:str]
    version: 3.13.1
