---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-ficsit-config
  namespace: games
data:
  installations.json: |
    {
      "selected_installation": "/config/gamefiles",
      "installations": [
        {
          "path": "/config/gamefiles",
          "profile": "Default",
          "vanilla": false
        }
      ],
      "version": 0
    }
  profiles.json: |
    {
      "profiles": {
        "Default": {
          "mods": {
            "Cartograph": {
              "version": "1.3.0",
              "enabled": true
            },
            "CurveBuilder": {
              "version": "1.2.1",
              "enabled": true
            },
            "InfiniteDismantle": {
              "version": "1.1.0",
              "enabled": true
            },
            "InfiniteNudge": {
              "version": "3.0.5",
              "enabled": true
            },
            "KBlueprintDesignPlus": {
              "version": "2026.2.260",
              "enabled": true
            }
          },
          "name": "Default",
          "required_targets": [
            "LinuxServer"
          ]
        }
      },
      "selected_profile": "Default",
      "version": 0
    }
