---
apiVersion: v1
kind: ConfigMap
metadata:
  name: satisfactory-ficsit-config
  namespace: games
data:
  installations.json: |
    {
      "selected_installation": "/config/gamefiles",
      "installations": [
        {
          "path": "/config/gamefiles",
          "profile": "Default",
          "vanilla": true
        }
      ],
      "version": 0
    }
  profiles.json: |
    {
      "profiles": {
        "Default": {
          "mods": {},
          "name": "Default",
          "required_targets": null
        }
      },
      "selected_profile": "Default",
      "version": 0
    }
