---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
  namespace: database
spec:
  postgresVersion: 16

  metadata:
    labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: "postgres"

  service:
    type: LoadBalancer
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres.boundcorp.net
        lbipam.cilium.io/ips: 10.20.30.209

  patroni:
    dynamicConfiguration:
      postgresql:
        max_wal_size: 5GB
        pg_hba:
          - hostssl all all all md5
        shared_preload_libraries: "pgvector"

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replica 1
      dataVolumeClaimSpec:
        storageClassName: nfs-nova-nvme
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: postgres

  databaseInitSQL:
    - name: devboxergo-init
      database: devboxergo
      sql: |
        CREATE EXTENSION IF NOT EXISTS pgvector;

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: recipes
      databases:
        - recipes
      password:
        type: AlphaNumeric
    - name: sonarr
      databases:
        - sonarr
      password:
        type: AlphaNumeric
    - name: devboxdaylight
      databases:
        - devboxdaylight
      password:
        type: AlphaNumeric
    - name: devboxzeroindex
      databases:
        - devboxzeroindex
      password:
        type: AlphaNumeric
    - name: devboxergo
      databases:
        - devboxergo
      password:
        type: AlphaNumeric
      options: "CREATEDB"


  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-postgres-secret
      global: &backupFlag
        compress-type: "bz2"
        compress-level: "9"
        # s3
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /crunchy-pgo
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
        repo1-s3-uri-style: path
        # minio
        # repo2-block: "y"
        # repo2-bundle: "y"
        # repo2-path: /crunchy-pgo
        # repo2-retention-full: "7" # days
        # repo2-retention-full-type: time
        # repo2-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1 # s3
          s3: &s3
            bucket: "boundcorp-backups-eu-north-1"
            endpoint: "https://s3.eu-north-1.amazonaws.com"
            region: "eu-north-1"
          schedules:
            full: "0 2 * * 0" # Sunday at 02:00
            incremental: "0 2 * * 1-6/2" # Mon-Sat at 02:00, every 2nd day
        # - name: repo2 # Minio
        #   s3: &minio
        #     bucket: "crunchy-postgres"
        #     endpoint: "s3.boundcorp.net"
        #     region: "us-east-1"
        #   schedules:
        #     full: "0 1 * * 0" # Sunday at 01:00
        #     differential: "0 1 * * 1-6" # Mon-Sat at 01:00
        #     incremental: "0 2-23 * * *" # Every hour except 01:00

  # dataSource:
  #   pgbackrest:
  #     stanza: "db"
  #     configuration: *backupConfig
  #     global: *backupFlag
  #     repo:
  #       name: "repo1"
  #       s3: *minio

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M

  proxy:
    pgBouncer:
      port: 5432
      replicas: *replica
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-pgbouncer
      config:
        global:
          pool_mode: "transaction" # pgBouncer is set to transaction for Authentik. Grafana requires session https://github.com/grafana/grafana/issues/74260#issuecomment-1702795311. Everything else is happy with transaction
          client_tls_sslmode: prefer
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: "pgbouncer"
