apiVersion: v1
kind: Secret
metadata:
    name: ghcr-boundcorp-pull
    namespace: database
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5AE7aKUBIMwNNOMLUhfDf52AwRufUgz4+55xhDHxlurtwLc26o0/TJ99kd0aKZnT0EpNPhj/QHomDrqR8v3PlYCGieFYrpyvxCexLIM/0i2sBIXdJbnq5DRS7a7k7N4IWwf45qZBUOXCoscEYplZD/43+DpZ0nzBvphppqeLnVfzqYr5IsYoWmLWf06lfu0XT/xpxAS27VjZBIYaNe3Mcmoo/txxcjscr4dwrU4fJCVrWef8ny4Q8EQr25HJvWvzQVciI2t+94f6ohltjozzCSCPKQEoxQUHGw3X5PaRckptx7OMBOK+Uh0JI6t2RAkLq+kT1z3MFNo/M37Td/Ix7eq9HR9yBZcFAHtbGm5RGjFCE21I5IjE9n4L2aU/WmMg7tICug==,iv:wIiyDMs7w1/+yGw6c+VwNwYiNZvzjPvRodswHkIbRCU=,tag:+QBVcrbAEnQWjdfZhh0NDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eW9SdnpkVVE1UFZhYTlW
            anliYmw2dzY2ME43QTk2TWtxUGlLZjU5TlJzCkl6Ny9VajYxdC9QcHh1Q1N5c2tu
            VkpOY2JxTS94Unovc0VvakVhZjVxbUkKLS0tIFJJQ2k3MGNJSWN6NE0yVi9Icm9a
            YzB5T1hUZVFaS3VyK0pLWHBBMnJWNFEK+oNURx7E/klplQSUvQL5tkERKrDe11kt
            cpznwAQoMTrr3NVBlNZ8SdskXMMwMdmxkxVEHQ/KdPNBuvIgonKT9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T19:05:45Z"
    mac: ENC[AES256_GCM,data:4mtxvBUoi3/giDxAIWjNQFZnFDPOfBWFBF+6qINytJ5HV9zXpDO4i2g5EjXeAn3jbaR6PANa0SEdxzWntwdjk0nNEC2piamkbSAMreAgkeJ3VtWitsNnH/iOwsKAvA0LId1KROWG8kehheQCGXUcJINEgk3CHdjcmIwsVPUYNCQ=,iv:NFpA8uGDPyfwf0opCPSwgkoAWcT3dSkN5bo/NII8rHE=,tag:jy/lIu12MJOdv23FcbIf6A==,type:str]
    version: 3.13.1
