apiVersion: v1
kind: Secret
metadata:
    name: speakr
    namespace: home
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:bA9/Sb7Y5oiF7j0Jb0zj45dlsyg8qOPQ4RecHU/Xi5Q=,iv:5sPIfk7IKVkgplbOdbkbIPUVPTop5VB+k4F0MKcWjMQ=,tag:PZNzmBmmqquvhN3ZuUOx3w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:rOHzluuAWaLG+eXhUZ7MLABE23LYuJi9cl3rN0i1XQpnhodjGAba4eI7ZZZ5SnRSJ+RY12R2BOUW9b+EimdwKw==,iv:Pkl3v3LRS6kUziC2A0DmZ6y1g7YvYhipRagfSesr3hI=,tag:zCJVp8LW7RqCaUvvIRalxg==,type:str]
    TEXT_MODEL_BASE_URL: ENC[AES256_GCM,data:gdPo7O8Q1njfbC3BQ9AvL5y1YOGOToy2hA==,iv:y3jJusB+ltdQ5NM6aTaEQHO9rNIdGnzyrhbdr4OPITY=,tag:IYf5l5vy86csqSu+t4afzw==,type:str]
    TEXT_MODEL_API_KEY: ENC[AES256_GCM,data:qhsDLx/X1SCdfQlXN7LYU58FH0SEfcjGLfj9nVAGRnZT75EMtlo5OimAX9pn+kV4Mg2skHLrn1jCWdSJ0NrY4bzBbnl7MW3kn2Mj208wl7QiRbsxDqgCQQsBykuUI6w9mP+ez4K7JXjV8x7J20VJNQgFxZp83XHr02oQJYUyOQwLzpBV2E1vxAQfIRAmYeJM21GiIuXFw25wLzJYiBoBxmzSZl4=,iv:YwZH5Lydy4upUbBxIUWiV9x9/W0JoLu0tqI1uQnzisM=,tag:3L9CTFStJLd4EDBKRpUKXg==,type:str]
    TEXT_MODEL_NAME: ENC[AES256_GCM,data:vCymN9RItRA+Kk8k,iv:PP33r2WN6ebop53xwiNzWOiB3OFK5NXWIkew71yzQHQ=,tag:iaWP+bD8Ie5YWzf1auesaQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:lv+asXL24BhivsqUnlpFSX5H9Vb8,iv:MVAcGS8rq601TRqPBmYrYR+KqEeuPRSuB7S5BWEfVr8=,tag:hutqhO6LWwlnD9FVn2F/Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbXVmeVFqTW1obndaSmdm
            WGlFZk9BdjFqV29MbTBRQXNVSUJhK3ZiRmlrCjcyRE42OTR2MHA4NzBmL3lVRnRu
            aHBia2dMSXJKZHh0ZDMwU3lRRm1VdkEKLS0tIDN0QTZ6dlBpZlNHNFlSU0Z1cVJ3
            eEVyZkxjSlhVb1NDZlhES0c0eDUxVkEKnl/hsWzkysGZdeKqXIOWEBdPNBze6WW/
            GTRQ204HdFEWfo5ZKu8PXLQW8JuAKR4l5gSawiE/+yhgaI1Nm8tTxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T18:44:48Z"
    mac: ENC[AES256_GCM,data:3/4MWVGkCt+tSNfALnsd9PnX0LULxN8HO5XtFtetKjoVsHkChxBpvF5xHUY5AzdBnIF7hl3+PQW4LihjwhNdq+O2QchGCvxYf+DZ+RTWuBWoO4Ae+CDEIM0nbvMajj1BawDl2koOPGkQL34k+PaYj8T3C72GyrN2U+QshTrBdgM=,iv:/nQLii3y0Oi86so4zjwvvNgYeQIm7dW3Stmgkzq9Mks=,tag:6FG3kvpWA95ivA/EQZDqww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
