apiVersion: v1
kind: Secret
metadata:
    name: speakr
    namespace: home
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:OHK4+f+Vg9dc4DmTqrT3fMeMLQaad36BQkTf726f6YM=,iv:GNvbt0XIdK66NO4LA3UV1K0wlTf9x22J2tUESzqcaro=,tag:Dhq3sSz8jX8ZhhNeRm8OAA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:VoPoVO8elQikrA8i4nHC1HxCJzp9Nku8Dt744giENz+qWEBp6sucAw8yCqgQ85jg9MsRtQ8F6F0crol/ONDV4Q==,iv:Ud6lniOdVggYwpGMluJ6snAfmhZtVZMo2t5ba8qtzIY=,tag:HkqFNtBukHHiQmI/zpPQmA==,type:str]
    TEXT_MODEL_BASE_URL: ENC[AES256_GCM,data:NctlP4lRHaPcnxwOoP+p50dr0Dff+rBbQA==,iv:mifSGUnBk/j0Ub8PKVSVbmccdh8aH2pCuKhHPpzkJ3Y=,tag:Gr/BgnXp0DNm13Z94Oe+LQ==,type:str]
    TEXT_MODEL_API_KEY: ENC[AES256_GCM,data:9JgUosyiA589OwYL93ASDXM5ypxuSERgbJ0YmCPSQq4XTGoiKNRBs/wYo9rj5spvOgn8OsATuX446Ay0KbymYir85Ou77Di+/UNkozwC8BoAmhkd/02N/VblcFN8EVME25Jd1svFuSeVlAtfuA6Ito1P0i7BB9ubRkFCZAUwd/LkOcKHNnTU+xk6s0a9/gmu54vzolBwwWQKVPJUNCW0aUl03w4=,iv:VtkdUHcEW1mnaGXQuBMFXMOsDVCBk01+mmqkxlmJXx8=,tag:hWZRscdpyP6u2eoq9P9ypA==,type:str]
    TEXT_MODEL_NAME: ENC[AES256_GCM,data:D52JJIPEI8h8TmHt,iv:TFyuaJfwXyI16EW8AIAeM/dN+UwRU3aA8SNSJSw3sJs=,tag:aW0Fjmk2FZgUw8FX+c0qMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TmptbnFEdERQa2ZBeWtv
            akkxV21EbzZ4QkhnR2M4a0xmZG1SK0JYaGlVCjBXaEpBZEdsNlkrMTZkc1UzVWFY
            U2tvUGc4dXlkUkluZWJFRHZNVjdTVU0KLS0tIDZNR2FKT0R1WlZIck1XbDBmczk4
            dTc4aVVDaHBqVEJmSDRsbUFJdHdBMVUK475J8Lm8zrOZa9aQ6Pa1x5ZmjD3FVpln
            tS8Tzz1jm9v6RcVyzlcP9/WgOOZF6BNzgx3jYnUbZ/OFGiT+a6742g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T18:33:51Z"
    mac: ENC[AES256_GCM,data:uBKHdYlWcrRANlah5D7B5IWU7TOUWk+GMxnh19k+B026PB7KMPeVArlnrfX9QIjre4vDp5KWyZ2Wvd+MfQFZVgjYa8bpb4y/ucD3F0mEEtJfjSUpfuj+Eo+tHhjg05z66s71AK6m3O1fviZ7KG2C9UsMUZlCNJdJPUhDDvXlYr0=,iv:p6zVYyIaTL22K4oOtI7sd7jDS22XQ4KcKlW4PBtvmPs=,tag:oUAvAFheAOAZs2glN2gu2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
