apiVersion: v1
kind: Secret
metadata:
    name: speakr
    namespace: home
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:hpnVz9LcVLeBQM8T9XlRoWCUQNv7ki43yKUENMpQiQA=,iv:XeArg0pFe0IIPPvMWYyKDddJEKn++Le8+KWgMdg4kME=,tag:lu00CNTeyYlobcNXTra+ag==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ozkMgHvyd60u6/dYagRGJJaWBjXJXGhv1Uk9FjBJJ4wh6sIikAx+9GKzH/BQhreMboduqwAElT+7QHWh3vlnog==,iv:um93Ky/2+eDj8KjB/fShoi1RskXmegZ3NsU5R5fx9o8=,tag:0MNRx5j/qYQ60GQ1OmnprQ==,type:str]
    TEXT_MODEL_BASE_URL: ENC[AES256_GCM,data:3fAcnsUpYU+DYGDjeU63NRmzu7ataVCHXA==,iv:OKhsApJ/8noCQSsztj7VxzMPDBh2Hp6bs70bXK09vYg=,tag:3XouDsGJbRrSeaXpxp9Mvg==,type:str]
    TEXT_MODEL_API_KEY: ENC[AES256_GCM,data:/fXSnzrZw/ctL4uvx5gTgvUIKlqlhU5gD0NCX9wTU4bjaDmPaxKnPYBMj5hsuMyoI8GEXEvbhhkVztGn+GLH/DPpekyRaatcc7JFdnXY0rzRrvM/4vxagpWrwjAeFY/i/GOWV5tMQjzYz0U24YZqp+CdnYxSf/TGXNkW983aUtLBFZNQWT7HPYK+iXUsuxKXljMRdstYeCAiB+Vt6SMkM3XCxXo=,iv:s0ZjODzn9kUQw1M97t563xJkzQuA4A/6sJJYZF38NZI=,tag:kL/Y5N/15c/PfR2LGxSNNQ==,type:str]
    TEXT_MODEL_NAME: ENC[AES256_GCM,data:KkVIboRKZ6+gma59,iv:Bxo9yH30FE72tEad6yM7tZnj8AMpunlTNvbsAsHEhH8=,tag:3AYK16AMcGd+obsAtUY/KQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:+JRf+cVyGP16ZSa5ghQOofFUwceO,iv:RL+hw6qRyaZTB166keJ7K44x+qtCNX8SJeAAVsepn3g=,tag:9Qbb6Ymrja6mBl4mdX9btw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age168rnvw24yn8722y6lnlax5rzvwpxqunaxdjef9vwjpkay8gyt3ssj4lqgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDRxUU54UmZqSjhKODdi
            S1N3cmJGNXpWSFV5R2Q4UGxBSGRZSzkzR1FzCm9aOXo0d3ZSUzRuNHJHdm5xYU1t
            TUd2TDNTNSs1Y3JKMVpvZGR6UDNMR0UKLS0tIDIzZkVlVnBQVmp2L2ZkVThrc2Q3
            Zm5BWUpFMjU5dWRWb2x3MmlvbFU5N2MK7Mk9qGmSyM94n5u8On6WA2d1IRkmE7wW
            sm4OxwJYNwxPA/qXNXRJq58afKMUFWHlMQ6P70bzDVQNAr6K5jMeqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T19:19:02Z"
    mac: ENC[AES256_GCM,data:CSy6ySM+YGjgDfJsjXEpJRw6cSxL+HVcEN11ZKsUhYk1C9oXmpXTgC1KpoIAPzS/IDne/i2EWTzFTA/F0VA7Tn0YSBZ4lLPltVuyYsUGSnM7DNkHBXejEhcQa6Ny/fXcuXNSkL79wVbh6YAM8jsONNxeLKQ7f+n/4TS458/4Q8o=,iv:SzF7t3fSW7vfqZV2VbbAK5zkWgANNLoAtXkjPfzQj0A=,tag:kzntD0EGBdMdCGrzISoCgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
